### ISSUE TITLE
Does not build with DMD 2.091

### ISSUE THREAD

**Issue by LightBender** [s-ludwig/taggedalgebraic#47]
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(77,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(85,9): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(93,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(101,9): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(109,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(117,9): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(125,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(133,9): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(141,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(157,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(173,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\taggedalgebraic-0.11.9\taggedalgebraic\source\taggedalgebraic\taggedalgebraic.d-mixin-76(189,4): Error: template identifier `FieldTypeByName` is not a member of alias `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion).TaggedAlgebraic.UnionType`
C:\Users\AdamWilson\AppData\Local\dub\packages\sdlang-d-0.10.5\sdlang-d\src\sdlang\parser.d(169,21): Error: template instance `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(ParserEventUnion)` error instantiating

**Comment by s-ludwig** [comment]
Can you post the instantiation of `TaggedAlgebraic` that triggers this? The unit tests and my code that uses it all compile fine.

**Comment by s-ludwig** [comment]
Closing for now, as this is not reproducible. Please reopen if this turned out to be an actual `TaggedAlgebraic` issue.
